services:
  backend:
    image: devops-product-backend
    container_name: devops-backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    image: devops-product-frontend
    container_name: devops-frontend
    ports:
      - "8082:80"
    depends_on:
      - backend
    restart: always
